export const words = [
  "LIVRE","RAMER","SALUT","MOTIF","TABLE","CHIEN","POMME","OCEAN",
  "ARBRE","PLAGE","MERCI","FORCE","TERRE","CABLE","CARTE","BOITE",
  "PLUIE","VENTE","NEIGE","NUAGE","FLEUR","HERBE","RAISE","MELON",
  "FRAIS","SUCRE","SELLE","MIELS","PAINS","SAUCE","EPICE","IMAGE",
  "VIDEO","AUDIO","RADIO","ECRAN","CLAVE","SOURI","LOGIC","DEBUG",
  "TESTS","OBJET","ROUTE","VILLE","HOTEL","ECOLE","LYCEE","ETUDE",
  "COURS","EXAME","SUJET","IDEES","PLANS","TEMPS","HEURE","TRAIN",
  "JOURS","NUITS","ANNEE","SPORT","COURT","NAGER","DANSE","CHANT",
  "PIANO","GUITA","FILME","SCENE","JEUNE","VIEUX","HOMME","FEMME",
  "AMOUR","AMITI","TRIST","CALME","RAPID","LENTE","GRAND","PETIT",
  "BEAUX","LAIDE","CLAIR","ROUGE","BLEUE","VERTS","NOIRS","TRAPE",
  "BLANC","GRISE","CHAUD","FROID","DROIT","HAUTE","BASSE"
]